
import {Model} from '@nozbe/watermelondb';
import {field} from '@nozbe/watermelondb/decorators';

class OrderLines extends Model {
	static table = 'order_lines';

	@field('id_order') idOrder!: string;
	@field('id_order_line') idOrderLine!: number;
	@field('picking_plant_number') pickingPlantNumber!: string;
	@field('storage_location') storageLocation!: string;
	@field('material_type') materialType!: string;
	@field('material_number') materialNumber!: string;
	@field('sequence') sequence!: number;
	@field('regular_quantity') regularQuantity!: number;
	@field('free_quantity') freeQuantity!: number;
	@field('total_quantity') totalQuantity!: number;
	@field('caliber') caliber!: number;
	@field('sales_unit') salesUnit!: string;
	@field('total_quantity_sales_unit') totalQuantitySalesUnit!: number;
	@field('gross_amount') grossAmount!: number;
	@field('net_amount') netAmount!: number;
	@field('automatic_rebate_percentage') automaticRebatePercentage!: number;
	@field('automatic_rebate_amount') automaticRebateAmount!: number;
	@field('id_promotion') idPromotion!: string;
	@field('color_item') colorItem!: string;
	@field('telesales_prime') telesalesPrime!: number;
	@field('promotion_item') promotionItem!: string;
	@field('item_category') itemCategory!: string;
	@field('wbs_element') wbsElement!: string;
	@field('id_free_item_reason') idFreeItemReason!: string;
	@field('approver_free_item_employee_number') approverFreeItemEmployeeNumber!: string;
	@field('specific_text') specificText!: string;
	@field('serial_number') serialNumber!: string;
	@field('manual_rebate_percentage') manualRebatePercentage!: number;
	@field('manual_rebate_amount') manualRebateAmount!: number;
	@field('free_text') freeText!: string;
	@field('gross_amount_free_quantity') grossAmountFreeQuantity!: number;
	@field('reference_price') referencePrice!: number;
	@field('net_weight') netWeight!: number;
	@field('gross_weight') grossWeight!: number;
	@field('leader_material_rebate_percentage') leaderMaterialRebatePercentage!: number;
	@field('leader_material_rebate_amount') leaderMaterialRebateAmount!: number;
	@field('hit_promo_rebate_percentage') hitPromoRebatePercentage!: number;
	@field('hit_promo_rebate_amount') hitPromoRebateAmount!: number;
	@field('stocks_datetime') stocksDatetime!: string;
	@field('stock_quantity') stockQuantity!: string;
	@field('stock_sales_unit') stockSalesUnit!: string;
	@field('quota_quantity') quotaQuantity!: string;
	@field('quota_sales_unit') quotaSalesUnit!: string;
	@field('change_reason_code') changeReasonCode!: string;
	@field('original_regular_quantity') originalRegularQuantity!: number;
	@field('original_free_quantity') originalFreeQuantity!: number;
	@field('original_caliber') originalCaliber!: number;
	@field('route_item') routeItem!: string;
	@field('change_reason_code_free_quantity') changeReasonCodeFreeQuantity!: string;
	@field('delivery_overcost_value') deliveryOvercostValue!: number;
	@field('delivery_overcost_non_full_case_value') deliveryOvercostNonFullCaseValue!: number;
	@field('opportunity_sled') opportunitySled!: string;
	@field('spot_price_percentage') spotPricePercentage!: number;
	@field('spot_price_amount') spotPriceAmount!: number;
	@field('spot_price_final_amount') spotPriceFinalAmount!: number;
	@field('spot_price_regular_material_value') spotPriceRegularMaterialValue!: number;
	@field('spot_price_opportunity_material_percentage') spotPriceOpportunityMaterialPercentage!: number;
	@field('spot_price_filled_data') spotPriceFilledData!: string;
	@field('spot_price_per_unit') spotPricePerUnit!: number;
	@field('spot_price_pricing_unit') spotPricePricingUnit!: string;
	@field('vat_amount') vatAmount!: number;
	@field('vat_rate') vatRate!: number;
	@field('net_net_price') netNetPrice!: number;
	@field('scale_rebate_amount') scaleRebateAmount!: number;
	@field('scale_rebate_percentage') scaleRebatePercentage!: number;
	@field('sequence_free') sequenceFree!: number;
	@field('product_out_of_stock') productOutOfStock!: string;
	@field('origin_order_line') originOrderLine!: string;
	@field('original_ines_qty') originalInesQty!: number;
	@field('customer_price') customerPrice!: number;
	@field('product_groups') productGroups!: string;
	@field('id_credit_order_reason') idCreditOrderReason!: string;
	@field('approver_credit_order_employee_number') approverCreditOrderEmployeeNumber!: string;
	@field('id_order_template') idOrderTemplate!: string;
	@field('data_origin') dataOrigin!: string;
	@field('last_sync_on') lastSyncOn!: string;
}

export default OrderLines;
