export const CREATE_PROSPECT_CONTROL_NAME = {
  TXT_PREVIOUS_CUSTOMER_SHIP_TO: 'txtPreviousCustomerShipTo',
  TXT_NAME: 'txtName',
  TXT_PHONENUMBER: 'txtPhoneNumber',
  TXT_ZIPCODE: 'txtZipCode',
  TXT_ADDRESS: 'txtAddress',
  TXT_STREET: 'txtStreetName',
  TXT_CITY: 'txtCity',
  TXT_ICE_CREAM_IMPLUSE: 'txtIceCreamImpluse',
  TXT_ICE_CREAM_BULK: 'txtIceCreamBulk',
  TXT_FROZEN_FOOD: 'txtFrozenFood',
  DDL_OUTLET: 'ddlOutletClassification',
  DDL_CUSTOMER_HIERARCHY: 'ddlCustomerHierarchy',
  DDL_COUNTRY: 'ddlCountry',
};

export const PLP_FINANCIAL_INFO_CONTROL_NAME = {
  DDL_Delivery_Note_Type: 'Cbo_FI_Delivery_Note_Type',
  DDL_INVOICE_RHYTHM: 'Cbo_FI_Cycle_Billing',
  DDL_REKAP: 'Cbo_FI_Rekap',
  DDL_PDF_INVOICING: 'Cbo_PDF_Invoicing',
};

export const PLP_FINANCIAL_INFO_ANDROID_CONTROL_NAME = {
  TXT_TAX_PAYER_ACCOUNT_NO: 'txtFITaxPayerAccountNo',
  TXT_SALES_TAX_ID_NO: 'txtFISalesTaxIdentificationNo',
  CB_TA_MINIMUM_TUROVER: 'cbFITAMinimumTurnoverExplained',
  TXT_EXPECTED_TURNOVER1: 'txtFIExpectedTurnOver1',
  TXT_EXPECTED_TURNOVER2: 'txtFIExpectedTurnOver2',
  TXT_EXPECTED_TURNOVER3: 'txtFIExpectedTurnOver3',
  DDL_DELIVERY_NOTE_TYPE: 'ddlFIDeliveryNotesType',
  DDL_INVOICE_RHYTHM: 'ddlFIInvoiceRhyme',
  DDL_REKAP: 'ddlFIRekap',
  DDL_PDF_INVOICING: 'ddlFIPdfInvoicing',
  TXT_EMAIL_PDF_INVOICING: 'txtFIEmailForPdfInvoicing',
  DDL_PAYMENT_TERMS: 'ddlFIPaymentTerms',
  DDL_PAYMENT_METHODS: 'ddlFIPaymentMethods',
};

export const PLP_CUSTOMER_ATTRIBUTE_INFO_ANDROID_CONTROL_NAME = {
  DDL_ABC_CLASSIFICATION: 'ddlCAAbcClassification',
  DDL_PRIORITY: 'ddlCAPriority',
  CB_SCOOPING: 'cbCAScooping',
  DP_START_BUSINESS_DATE: 'dpCAStartBusinessDate',
  DDL_BUSINESS_REASON: 'ddlCAStartBusinessReason',
  TXT_KEY_ACCOUNT_GLN_CODE: 'txtCAKeyAccountGLNCode',
  CB_INDIRECT_CUSTOMER: 'cbCAIndirectCustomer',
  TXT_WHOLE_SALER_CUSTOMER_NO: 'txtCAWholeSalerCustomerNo',
  DDL_DISTRIBUTOR: 'ddlCADistributor',
  TXT_FIRST_NAME: 'txtCAFirstName',
  TXT_LAST_NAME: 'txtCALastName',
  DDL_NAME: 'ddlCAFSRName',
};

export const DROPDOWN_CONTROL_NAME = {
  COUNTRY_SHIP_TO: 'Cbo_Country_Ship_To',
  SHIP_TO_DISTRIBUTION_CHANNEL: 'Cbo_Ship_To_Distribution_Channel',
  TA_DESIGN: 'Cbo_TA_Design',
  FOLLOW_UP_ACTIONS: 'Cbo_Follow_Up_Actions',
};

export const PLP_SHIP_TO_CONTROL_NAME = {
  TXT_PREVIOUS_CUSTOMER_SHIP_TO: 'txtShipToPreviousCustomerShipTo',
  TXT_NAME1: 'txtShipToName1',
  TXT_NAME2: 'txtShipToName2',
  TXT_NAME3: 'txtShipToName3',
  TXT_NAME4: 'txtShipToName4',
  TXT_EMAIL: 'txtShipToEmail',
  TXT_PHONE_NO: 'txtShipToPhoneNo',
  TXT_MOBILE_NO: 'txtShipToMobileNo',
  TXT_FAX: 'txtShipToFaxNo',
  TXT_HOUSE_NO: 'txtShipToHouseNo',
  TXT_ADDRESS1: 'txtShipToAddress1',
  TXT_ADDRESS2: 'txtShipToAddress2',
  TXT_ADDRESS3: 'txtShipToAddress3',
  TXT_ZIP_CODE: 'txtShipToZipCode',
  TXT_PO_BOX: 'txtShipToPOBox',
  TXT_CITY: 'txtShipToCity',
  TXT_CO: 'txtShipToCO', // CONTROL NAME NOT CONFIGURED
  TXT_LATITUDE: 'txtShipToLatitude', // CONTROL NAME NOT CONFIGURED
  TXT_LONGTITUDE: 'txtShipToLongitude', // CONTROL NAME NOT CONFIGURED
  TXT_WEBSITE: 'txtShipToWebSite',
  TXT_SHOP_NO: 'txtShipToShopNo',
  DDL_SALES_AREA: 'ddlShipToSalesArea', // CONTROL NAME NOT CONFIGURED
  DDL_CUSTOMER_HIERARCHY: 'ddlShipToCustomerHierarchy',
  DDL_OUTLET: 'ddlShipToOutletClassification',
  DDL_DISTRIBUTION_CHANNEL: 'ddlShipToDistributionChannel',
  DDL_COUNTRY: 'ddlShipToCountry',
  DDL_LANGUAGE: 'ddlShipToLanguage',
};

export const PLP_BILL_TO_CONTROL_NAME = {
  TXT_NAME1: 'txtBillToName1',
  TXT_NAME2: 'txtBillToName2',
  TXT_NAME3: 'txtBillToName3',
  TXT_NAME4: 'txtBillToName4',
  TXT_EMAIL: 'txtBillToEmail',
  TXT_PHONE_NO: 'txtBillToPhoneNo',
  TXT_MOBILE_NO: 'txtBillToMobileNo',
  TXT_FAX: 'txtBillToFaxNo',
  TXT_HOUSE_NO: 'txtBillToHouseNo',
  TXT_ADDRESS1: 'txtBillToAddress1',
  TXT_ADDRESS2: 'txtBillToAddress2',
  TXT_ADDRESS3: 'txtBillToAddress3',
  TXT_ZIP_CODE: 'txtBillToZipCode',
  TXT_PO_BOX: 'txtBillToPoBox',
  TXT_POSTAL_CODE_PO_BOX: 'txtBillToPostalCodePOBox',
  TXT_CITY_PO_BOX: 'txtBillToCityPOBox',
  TXT_CITY: 'txtBillToCity',
  DDL_COUNTRY: 'ddlBillToCountry',
};

export const PLP_DELIVERY_ADDRESS_CONTROL_NAME = {
  TXT_NAME1: 'txtDeliveryAddressName1',
  TXT_NAME2: 'txtDeliveryAddressName2',
  TXT_NAME3: 'txtDeliveryAddressName3',
  TXT_NAME4: 'txtDeliveryAddressName4',
  TXT_EMAIL: 'txtDeliveryAddressEmail',
  TXT_PHONE_NO: 'txtDeliveryAddressPhoneNo',
  TXT_MOBILE_NO: 'txtDeliveryAddressMobileNo',
  TXT_FAX: 'txtDeliveryAddressFaxNo',
  TXT_HOUSE_NO: 'txtDeliveryAddressHouseNo',
  TXT_ADDRESS1: 'txtDeliveryAddressAddress1',
  TXT_ADDRESS2: 'txtDeliveryAddressAddress2',
  TXT_ADDRESS3: 'txtDeliveryAddressAddress3',
  TXT_ZIP_CODE: 'txtDeliveryAddressZipCode',
  TXT_PO_BOX: 'txtDeliveryAddressPoBox',
  TXT_POSTAL_CODE_PO_BOX: 'txtDeliveryAddressPostalCodePOBox',
  TXT_CITY_PO_BOX: 'txtDeliveryAddressCityPOBox',
  TXT_CITY: 'txtDeliveryAddressCity',
  DDL_COUNTRY: 'ddlDeliveryAddressCountry',
};

export const PLP_RCA_CONTROL_NAME = {
  DDL_OPENING_MON_MORNING_FROM: 'ddlRcaOpeningMonMorningFrom',
  DDL_OPENING_MON_MORNING_TO: 'ddlRcaOpeningMonMorningTo',
  DDL_OPENING_MON_AFTERNOON_FROM: 'ddlRcaOpeningMonAfternoonFrom',
  DDL_OPENING_MON_AFTERNOON_TO: 'ddlRcaOpeningMonAfternoonTo',
  DDL_OPENING_TUE_MORNING_FROM: 'ddlRcaOpeningTueMorningFrom',
  DDL_OPENING_TUE_MORNING_TO: 'ddlRcaOpeningTueMorningTo',
  DDL_OPENING_TUE_AFTERNOON_FROM: 'ddlRcaOpeningTueAfternoonFrom',
  DDL_OPENING_TUE_AFTERNOON_TO: 'ddlRcaOpeningTueAfternoonTo',
  DDL_OPENING_WED_MORNING_FROM: 'ddlRcaOpeningWedMorningFrom',
  DDL_OPENING_WED_MORNING_TO: 'ddlRcaOpeningWedMorningTo',
  DDL_OPENING_WED_AFTERNOON_FROM: 'ddlRcaOpeningWedAfternoonFrom',
  DDL_OPENING_WED_AFTERNOON_TO: 'ddlRcaOpeningWedAfternoonTo',
  DDL_OPENING_THU_MORNING_FROM: 'ddlRcaOpeningThuMorningFrom',
  DDL_OPENING_THU_MORNING_TO: 'ddlRcaOpeningThuMorningTo',
  DDL_OPENING_THU_AFTERNOON_FROM: 'ddlRcaOpeningThuAfternoonFrom',
  DDL_OPENING_THU_AFTERNOON_TO: 'ddlRcaOpeningThuAfternoonTo',
  DDL_OPENING_FRI_MORNING_FROM: 'ddlRcaOpeningFriMorningFrom',
  DDL_OPENING_FRI_MORNING_TO: 'ddlRcaOpeningFriMorningTo',
  DDL_OPENING_FRI_AFTERNOON_FROM: 'ddlRcaOpeningFriAfternoonFrom',
  DDL_OPENING_FRI_AFTERNOON_TO: 'ddlRcaOpeningFriAfternoonTo',
  DDL_OPENING_SAT_MORNING_FROM: 'ddlRcaOpeningSatMorningFrom',
  DDL_OPENING_SAT_MORNING_TO: 'ddlRcaOpeningSatMorningTo',
  DDL_OPENING_SAT_AFTERNOON_FROM: 'ddlRcaOpeningSatAfternoonFrom',
  DDL_OPENING_SAT_AFTERNOON_TO: 'ddlRcaOpeningSatAfternoonTo',
  DDL_OPENING_SUN_MORNING_FROM: 'ddlRcaOpeningSunMorningFrom',
  DDL_OPENING_SUN_MORNING_TO: 'ddlRcaOpeningSunMorningTo',
  DDL_OPENING_SUN_AFTERNOON_FROM: 'ddlRcaOpeningSunAfternoonFrom',
  DDL_OPENING_SUN_AFTERNOON_TO: 'ddlRcaOpeningSunAfternoonTo',
  DDL_VISITING_MON_MORNING_FROM: 'ddlRcaVisitingMonMorningFrom',
  DDL_VISITING_MON_MORNING_TO: 'ddlRcaVisitingMonMorningTo',
  DDL_VISITING_MON_AFTERNOON_FROM: 'ddlRcaVisitingMonAfternoonFrom',
  DDL_VISITING_MON_AFTERNOON_TO: 'ddlRcaVisitingMonAfternoonTo',
  DDL_VISITING_TUE_MORNING_FROM: 'ddlRcaVisitingTueMorningFrom',
  DDL_VISITING_TUE_MORNING_TO: 'ddlRcaVisitingTueMorningTo',
  DDL_VISITING_TUE_AFTERNOON_FROM: 'ddlRcaVisitingTueAfternoonFrom',
  DDL_VISITING_TUE_AFTERNOON_TO: 'ddlRcaVisitingTueAfternoonTo',
  DDL_VISITING_WED_MORNING_FROM: 'ddlRcaVisitingWedMorningFrom',
  DDL_VISITING_WED_MORNING_TO: 'ddlRcaVisitingWedMorningTo',
  DDL_VISITING_WED_AFTERNOON_FROM: 'ddlRcaVisitingWedAfternoonFrom',
  DDL_VISITING_WED_AFTERNOON_TO: 'ddlRcaVisitingWedAfternoonTo',
  DDL_VISITING_THU_MORNING_FROM: 'ddlRcaVisitingThuMorningFrom',
  DDL_VISITING_THU_MORNING_TO: 'ddlRcaVisitingThuMorningTo',
  DDL_VISITING_THU_AFTERNOON_FROM: 'ddlRcaVisitingThuAfternoonFrom',
  DDL_VISITING_THU_AFTERNOON_TO: 'ddlRcaVisitingThuAfternoonTo',
  DDL_VISITING_FRI_MORNING_FROM: 'ddlRcaVisitingFriMorningFrom',
  DDL_VISITING_FRI_MORNING_TO: 'ddlRcaVisitingFriMorningTo',
  DDL_VISITING_FRI_AFTERNOON_FROM: 'ddlRcaVisitingFriAfternoonFrom',
  DDL_VISITING_FRI_AFTERNOON_TO: 'ddlRcaVisitingFriAfternoonTo',
  DDL_VISITING_SAT_MORNING_FROM: 'ddlRcaVisitingSatMorningFrom',
  DDL_VISITING_SAT_MORNING_TO: 'ddlRcaVisitingSatMorningTo',
  DDL_VISITING_SAT_AFTERNOON_FROM: 'ddlRcaVisitingSatAfternoonFrom',
  DDL_VISITING_SAT_AFTERNOON_TO: 'ddlRcaVisitingSatAfternoonTo',
  DDL_VISITING_SUN_MORNING_FROM: 'ddlRcaVisitingSunMorningFrom',
  DDL_VISITING_SUN_MORNING_TO: 'ddlRcaVisitingSunMorningTo',
  DDL_VISITING_SUN_AFTERNOON_FROM: 'ddlRcaVisitingSunAfternoonFrom',
  DDL_VISITING_SUN_AFTERNOON_TO: 'ddlRcaVisitingSunAfternoonTo',
  SEASON: 'ddlRcaSeason',
  CALL_FREQUENCY: 'ddlRcaCallFrequency',
  CALL_WEEK: 'ddlRcaCallWeek',
  DELIVERY_WEEK: 'ddlRcaDeliveryWeek',
  DISTRIBUTION_CENTER: 'ddlRcaDistributionCenter',
  TRANSIT_CALL_PLACE: 'ddlRcaTransitCallPlace',
  CALL_DAY_MONDAY: 'cbRcaCallDayMonday',
  CALL_DAY_TUESDAY: 'cbRcaCallDayTuesday',
  CALL_DAY_WEDNESDAY: 'cbRcaCallDayWednesday',
  CALL_DAY_THURSDAY: 'cbRcaCallDayThursday',
  CALL_DAY_FRIDAY: 'cbRcaCallDayFriday',
  CALL_DAY_SATURDAY: 'cbRcaCallDaySaturday',
  CALL_DAY_SUNDAY: 'cbRcaCallDaySunday',
  DELIVERY_DAY_MONDAY: 'ddlRcaDeliveryDayMonday',
  DELIVERY_DAY_TUESDAY: 'ddlRcaDeliveryDayTuesday',
  DELIVERY_DAY_WEDNESDAY: 'ddlRcaDeliveryDayWednesday',
  DELIVERY_DAY_THURSDAY: 'ddlRcaDeliveryDayThursday',
  DELIVERY_DAY_FRIDAY: 'ddlRcaDeliveryDayFriday',
  DELIVERY_DAY_SATURDAY: 'ddlRcaDeliveryDaySaturday',
  DELIVERY_DAY_SUNDAY: 'ddlRcaDeliveryDaySunday',
  NOTES: 'txtRcaNotes',
};

export const PLP_CONTACTS_CONTROL_NAME = {
  DDL_CONTACTS1_TITLE: 'ddlContacts1Title',
  TXT_CONTACTS1_FIRST_NAME: 'txtContacts1FirstName',
  TXT_CONTACTS1_LAST_NAME: 'txtContacts1LastName',
  TXT_CONTACTS1_PHONE_NO: 'txtContacts1PhoneNumber',
  TXT_CONTACTS1_MOBILE_NO: 'txtContacts1MobileNumber',
  TXT_CONTACTS1_FAX_NO: 'txtContacts1FaxNumber',
  TXT_CONTACTS1_EMAIL: 'txtContacts1Email',
  TXT_CONTACTS1_NOTES: 'txtContacts1Notes',
  DDL_CONTACTS2_TITLE: 'ddlContacts2Title',
  TXT_CONTACTS2_FIRST_NAME: 'txtContacts2FirstName',
  TXT_CONTACTS2_LAST_NAME: 'txtContacts2LastName',
  TXT_CONTACTS2_PHONE_NO: 'txtContacts2PhoneNumber',
  TXT_CONTACTS2_MOBILE_NO: 'txtContacts2MobileNumber',
  TXT_CONTACTS2_FAX_NO: 'txtContacts2FaxNumber',
  TXT_CONTACTS2_EMAIL: 'txtContacts2Email',
  TXT_CONTACTS2_NOTES: 'txtContacts2Notes',
};

export const PLP_SEPA_CONTROL_NAME = {
  TXT_NAME_OF_ACCOUNT_HOLDER: 'txtSepaNameOfAccountHolder',
  TXT_SEPA_IBAN_NO: 'txtSepaIBANNumber',
  SIGN_CUSTOMER_SIGNATURE: 'signSepaCustomerSignature',
};
